server:
  port: 8081
spring:
  application:
    name: member-service
  config:
    import: "optional:configserver:http://localhost:8888/"
    fail-fast: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
  data:
    redis:
      host: localhost
      port: 6379
app:
  frontend:
    url: http://localhost:5173
  cookie:
    secure: false # localhost 면 false
    same-site: Lax
    access-token-name: access_token
    refresh-token-name: refresh_token
auth:
  access-token-secret: ${JWT_SECRET:qkxSN1Y9eZUJN7FrqGrZ1antggnBvfXplgh9T5qOzs29V8DlfCm/pcZKmlsooChcEvSqidmIUmGKy8xjlKUBqg}
  access-token-expiration: 1800000ms      # 30분
  refresh-token-expiration: 604800000ms   # 7일