drop database if exists chohj_seller;
create database chohj_seller character set utf8;

drop table seller;
CREATE TABLE seller (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled              BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_locked   BOOLEAN NOT NULL DEFAULT TRUE,
    created_date         TIMESTAMP,
    updated_date         TIMESTAMP,
);
select * from seller;