drop database if exists chohj_board;
create database chohj_board character set utf8;

DROP TABLE board;
CREATE TABLE board (
    no                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_type           VARCHAR(15) NOT NULL,
    title                VARCHAR(255) NOT NULL,
    content              VARCHAR(65535) NOT NULL,
    created_date         TIMESTAMP,
    updated_date         TIMESTAMP
)
select * from board;

CREATE TABLE board_display_post (
    no                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_no           BIGINT NOT NULL,
    display_order      INT NOT NULL,
    display_start_date TIMESTAMP,
    display_end_date   TIMESTAMP,
    active             BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_board_display_post_board FOREIGN KEY (board_no) REFERENCES board (no),
);
