drop database if exists chohj_board;
create database chohj_board character set utf8;

drop table board_notification;
CREATE TABLE board_notification (
    no                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                VARCHAR(255),
    content              VARCHAR(65535),
    member_id            BIGINT NOT NULL,
    created_date         TIMESTAMP,
    updated_date         TIMESTAMP
);
select * from board_notification;

DROP TABLE board_event;
CREATE TABLE board_event (
    no                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                VARCHAR(255),
    content              VARCHAR(65535),
    member_id            BIGINT NOT NULL,
    created_date         TIMESTAMP,
    updated_date         TIMESTAMP
)
select * from board_event;