DROP DATABASE IF EXISTS chohj_member;
CREATE DATABASE chohj_member ENCODING 'UTF8';

CREATE TABLE member (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255),
    name            VARCHAR(255),
    role            VARCHAR(255),
    creation_date   TIMESTAMP,
    update_date     TIMESTAMP,
    CONSTRAINT uk_member_email UNIQUE (email)
);

CREATE TABLE social_account (
    id              VARCHAR(255) PRIMARY KEY,
    provider_type   VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    member_id       BIGINT NOT NULL,
    creation_date   TIMESTAMP,
    update_date     TIMESTAMP
);