DROP DATABASE IF EXISTS chohj_member;
CREATE DATABASE chohj_member ENCODING 'UTF8';

drop table member;
CREATE TABLE member (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(255) NOT NULL,
    password             VARCHAR(255),
    name                 VARCHAR(255),
    enabled              BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_locked   BOOLEAN NOT NULL DEFAULT TRUE,
    created_date         TIMESTAMP,
    updated_date         TIMESTAMP,
    CONSTRAINT uk_member_email UNIQUE (email)
);
select * from member;

drop table member_roles;
CREATE TABLE member_roles (
    member_id   BIGINT NOT NULL,
    role        VARCHAR(255) NOT NULL,
    CONSTRAINT member_roles_pkey PRIMARY KEY (member_id, role),
    CONSTRAINT fk_member_roles_member FOREIGN KEY (member_id) REFERENCES member (id)
);
select * from member_roles;

drop table social_account;
CREATE TABLE social_account (
    id              VARCHAR(255) PRIMARY KEY,
    provider_type   VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    member_id       BIGINT NOT NULL,
    creation_date   TIMESTAMP,
    update_date     TIMESTAMP,
    CONSTRAINT fk_social_account_member
        FOREIGN KEY (member_id) REFERENCES member (id)
);
select * from social_account;
