drop database if exists chohj_seller;
create database chohj_seller character set utf8;

drop table board_notification;
CREATE TABLE board_notification (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                BOOLEAN NOT NULL DEFAULT TRUE,
    content              BOOLEAN NOT NULL DEFAULT TRUE,
    created_date         TIMESTAMP,
    updated_date         TIMESTAMP,
);
select * from board_notification;